### PR TITLE
Import and Export.

### PR DESCRIPTION
**Pull request by zylvyn**
Adding import to and export from a file.  Import allows specification of file, export allows specification of save-to directory.

---

This change is [Reviewable](https://reviewable.io/reviews/achaeabashingscript/bashing/41)

### CODE REVIEW

**Comment by keneanung** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdyWptNODGOOfWHanz:-KMdyWpu1dYDKiSYA7ip:-1668083536) (no related file):*
Generally,​ this is a very simple import / export. I am still pondering, though ​if I had more of a "sync" in mind...

This is great for getting a headstart on a new profile or providing a new player with the first priorities. But if an existing player used different computers/profiles and optimized priorities on one to sync with the others, this doesn't help too much: deletions and different priorities are not handled.

On the other hand, I have no idea how to let the user solve those conflicts and if it's not overcomplicating things...

---

*[script.lua, line 1646 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMduvKoABL1pwrjZXFx:-KMduvKoABL1pwrjZXFy:-1042495393) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1646)):*
> ```Lua
> 
> keneanung.bashing.export = function()
> 	local directory = invokeFileDialog(false, "Which do you want to export your priorities to?")
> ```

I believe there's a `file` missing here.

---

*[script.lua, line 1651 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdvZjvdX-UK85AKsaR:-KMdvZjvdX-UK85AKsaS:1209436995) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1651)):*
> ```Lua
> 		if string.char(getMudletHomeDir():byte()) == "/" then
> 			sep = "/" else sep = "\\"
> 		end
> ```

This is what I used in the `load` script. However, I learned that lua can magically convert path separators and this may only be needed for display purposes (if at all?). Could you test how it looks with forward slashes only?

---

*[script.lua, line 1653 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdw5aUDJkjXKrCdw7f:-KMdw5aUDJkjXKrCdw7g:-727268260) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1653)):*
> ```Lua
> 		end
> 		table.save(directory.. sep .. "Bashing-Export.lua", keneanung.bashing.configuration.priorities) -- Exporting to folder specified
> 		kecho("Have exported priorities to " .. path .. sep .. "Bashing-Export.lua") -- Messaging user
> ```

I usually colour variable​ things so the user knows at a glance where they start and end.

---

*[script.lua, line 1667 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdxblTZwXlOUDbwH-u:-KMdxblTZwXlOUDbwH-v:1046382847) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1667)):*
> ```Lua
> 					keneanung.bashing.configuration.priorities[area] = {}
> 				end
> 				for index,denizenString in pairs(importTable[area]) do
> ```

Also just noticed: you don't use the `index`, so you should use `_` to make this clear.

---

*[script.lua, line 1669 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdwo9FKNXSBWHLRFtg:-KMdwo9FKNXSBWHLRFth:521762501) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1669)):*
> ```Lua
> 				for index,denizenString in pairs(importTable[area]) do
> 					if not table.contains(keneanung.bashing.configuration.priorities[area],denizenString) then
> 						keneanung.bashing.configuration.priorities[area][#keneanung.bashing.configuration.priorities[area]+1] = denizenString
> ```

Just noticed a bug here: You are looping over the table with `pairs` which **does not guarantee** the order of indexed tables. However here you are adding the denizen string to the end, disregarding the possible randomness of `pairs`. You should use `ipairs` instead.

The same goes for the `guhemImport` function above.

---

*[script.lua, line 1673 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdvG_IatjVw9zvPzS0:-KMdvG_IatjVw9zvPzS1:908721464) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1673)):*
> ```Lua
> 				end
> 			end
> 		end
> ```

This loop is a copy of the one at `guhemImport()`. Can you extract it to a local function which receives​ the table to import?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by keneanung** [comment]
Bleh... Reviewable makes it pretty hard to read those comments here. They are easier to read over there (https://reviewable.io/reviews/achaeabashingscript/bashing/41)

**Comment by zylvyn** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdyWptNODGOOfWHanz:-KXHsM3df0ne8M8Kr5oV:b-cseuk8) (no related file):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> Generally,​ this is a very simple import / export. I am still pondering, though ​if I had more of a "sync" in mind...
> 
> This is great for getting a headstart on a new profile or providing a new player with the first priorities. But if an existing player used different computers/profiles and optimized priorities on one to sync with the others, this doesn't help too much: deletions and different priorities are not handled.
> 
> On the other hand, I have no idea how to let the user solve those conflicts and if it's not overcomplicating things...
</details>
Sync is a bit more of a complex thing, especially between multiple computers.  I guess the real question is, is there a large need for sync?  How often do you really start hunting in a new area on multiple computers, and couldn't you simply export to Dropbox and reimport if that were the case?

I've wanted to have sync for a couple of my scripts now, but it just didn't seem worth the headache for the scope of it.  This project might be big enough to bother, though.

Once SVO Multiclass comes out, fewer people will have multiple 'profiles' at least... although as someone that hops about between 4 computers myself, I can definitely appreciate this aspect of it.

---

*[script.lua, line 1646 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMduvKoABL1pwrjZXFx:-KXHpopdhB8YQy1L7iLb:b-896fix) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1646)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> I believe there's a `file` missing here.
</details>
Done.

---

*[script.lua, line 1651 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdvZjvdX-UK85AKsaR:-KXHpmiqBGvD7WQ4AbP2:b-896fix) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1651)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> This is what I used in the `load` script. However, I learned that lua can magically convert path separators and this may only be needed for display purposes (if at all?). Could you test how it looks with forward slashes only?
</details>
Done.

---

*[script.lua, line 1667 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdxblTZwXlOUDbwH-u:-KXHptK13LJ0r39RAwA2:b-896fix) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1667)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> Also just noticed: you don't use the `index`, so you should use `_` to make this clear.
</details>
Done.

---

*[script.lua, line 1669 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdwo9FKNXSBWHLRFtg:-KXHr0FD1qYUDCSnawWQ:b-896fix) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1669)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> Just noticed a bug here: You are looping over the table with `pairs` which **does not guarantee** the order of indexed tables. However here you are adding the denizen string to the end, disregarding the possible randomness of `pairs`. You should use `ipairs` instead.
> 
> The same goes for the `guhemImport` function above.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by zylvyn** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[script.lua, line 1653 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdw5aUDJkjXKrCdw7f:-KXHt6fbiNWsOm2aPoYI:b-ac4ts9) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1653)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> I usually colour variable​ things so the user knows at a glance where they start and end.
</details>
Am I imagining things, or were you pondering theming of the hunting script at one point or another?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by keneanung** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdyWptNODGOOfWHanz:-KXI8A3xtFqHGivZeAGV:b-bfpvab) (no related file):*
<details><summary><i>Previously, zylvyn (Zylvyn) wrote…</i></summary>
> Sync is a bit more of a complex thing, especially between multiple computers.  I guess the real question is, is there a large need for sync?  How often do you really start hunting in a new area on multiple computers, and couldn't you simply export to Dropbox and reimport if that were the case?
> 
> I've wanted to have sync for a couple of my scripts now, but it just didn't seem worth the headache for the scope of it.  This project might be big enough to bother, though.
> 
> Once SVO Multiclass comes out, fewer people will have multiple 'profiles' at least... although as someone that hops about between 4 computers myself, I can definitely appreciate this aspect of it.
</details>
OK, you're probably right. Maybe put that back to later.

---

*[script.lua, line 1651 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdvZjvdX-UK85AKsaR:-KXI82K57ygaGhzrLDAb:b-92aajx) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1651)):*
<details><summary><i>Previously, zylvyn (Zylvyn) wrote…</i></summary>
> Done.
</details>
I can't see any difference here

---

*[script.lua, line 1653 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdw5aUDJkjXKrCdw7f:-KXI7Y0oJqukZuJbQ2Eq:b-wub7qd) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1653)):*
<details><summary><i>Previously, zylvyn (Zylvyn) wrote…</i></summary>
> Am I imagining things, or were you pondering theming of the hunting script at one point or another?
</details>
I do, I even started a branch for it a while back (I think). But that's for when I have nothing else to do. (So never?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by zylvyn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[script.lua, line 1651 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdvZjvdX-UK85AKsaR:-KXINdoovplzIWFe9HbS:b-e8ziab) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1651)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> I can't see any difference here
</details>
Yeah... I'm still learning with gitkraken.  >.>

How about now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by zylvyn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[script.lua, line 1653 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdw5aUDJkjXKrCdw7f:-KXIP6Hc3zrKVBzPrRnJ:bz2sk31) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1653)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> I do, I even started a branch for it a while back (I think). But that's for when I have nothing else to do. (So never?)
</details>
Okay.  Well, got this to at least the current paradigm, if not the themed variant!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by zylvyn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[script.lua, line 1673 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdvG_IatjVw9zvPzS0:-KXIUir21qXePglNr6xm:b-3tmtzy) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1673)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> This loop is a copy of the one at `guhemImport()`. Can you extract it to a local function which receives​ the table to import?
</details>
Done.

Commit: b4a6a327089156f851f89e9056dd8c85337d69cf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by keneanung** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[script.lua, line 1651 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdvZjvdX-UK85AKsaR:-KXKNuH3WBEc8az_alfK:bj2v70h) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1651)):*
<details><summary><i>Previously, zylvyn (Zylvyn) wrote…</i></summary>
> Yeah... I'm still learning with gitkraken.  >.>
> 
> How about now?
</details>
Still no change. Did you push to a different branch or forget to push at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by zylvyn** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[script.lua, line 1651 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdvZjvdX-UK85AKsaR:-KXLZeWwtWNsGqaMgavZ:bs6hbnb) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1651)):*
>.>   Okay, NOW.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41)*

**Comment by keneanung** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[script.lua, line 1653 at r1](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-KMdw5aUDJkjXKrCdw7f:-KXL_mppi0LgdtmEVcEn:bb6ywmx) ([raw file](https://github.com/achaeabashingscript/bashing/blob/dc95e8b3b12df6a97e2e5112bd05460b492eb89e/script.lua#L1653)):*
<details><summary><i>Previously, zylvyn (Zylvyn) wrote…</i></summary>
> Okay.  Well, got this to at least the current paradigm, if not the themed variant!
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/41#-:-KXL_sXS4fSQv8mevDF5:bnfp4nl)*

**Pull request merged**
