### PR TITLE
Adding event for settings change

### PR DESCRIPTION
**Pull request by codeacula**
This used to be in the bashing sytem but was removed. I'm hoping we can add it back since I relied on being notified when settings changed to update button colors

### CODE REVIEW

**Comment by keneanung** [comment]
Could you add the other places where config settings are changed as well? For example flee settings are not triggering this event.

**Comment by codeacula** [comment]
Got everywhere I could see the settings being updated

**Comment by keneanung** [comment]
The `shuffleUp`, `shuffleDown` and `keneanung.bashing.delete` are still missing the event as you added it to the `addPossibleTarget`. `keneanung.bashing.deleteFile` also doesn't have an event.

**Comment by codeacula** [comment]
Added!

**Review by keneanung — APPROVED** [review]
Thanks for contributing your improvement :smile:

**Pull request merged**
