### PR TITLE
Guhem Targetting script import

### PR DESCRIPTION
**Pull request by zylvyn**
[Issue 21](https://github.com/AchaeaBashingScript/Bashing/issues/21) Importing from Guhem's script.

---
This change is [Reviewable](https://reviewable.io/reviews/achaeabashingscript/bashing/40)

### CODE REVIEW

**Comment by keneanung** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[script.lua, line 1631 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/40#-KMOVc3Kj9WK3CBozI29:-KMOVc3Kj9WK3CBozI2A:1575925533) ([raw file](https://github.com/achaeabashingscript/bashing/blob/a569783a7de58971bc6889af276bb81751787d29/script.lua#L1631)):*
> ```Lua
> 
> keneanung.bashing.guhemImport = function()
> 	for k in pairs(huntVar.userAreaList) do
> ```

Not to be nit-picky, but could you make the variables a little more readable (i.e. `area` in this case)?

---

*[script.lua, line 1636 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/40#-KMOWBDJdI-0-Srya4mo:-KMOWBDKrDxgSCCucPQ1:953968996) ([raw file](https://github.com/achaeabashingscript/bashing/blob/a569783a7de58971bc6889af276bb81751787d29/script.lua#L1636)):*
> ```Lua
> 				keneanung.bashing.configuration.priorities[k] = {}
> 			end
> 			for i,v in pairs(huntVar.userAreaList[k]) do
> ```

Same here as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/40)*

**Comment by zylvyn** [comment]
Should be more betterer now.

**Comment by keneanung** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/40#-:-KMOtyHqMoZiUQiUpa-i:1417088721)*

**Comment by keneanung** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[script.lua, line 1631 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/40#-KMOVc3Kj9WK3CBozI29:-KMOu88pCWmERJVPt6Kt:5173665) ([raw file](https://github.com/achaeabashingscript/bashing/blob/a569783a7de58971bc6889af276bb81751787d29/script.lua#L1631)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> Not to be nit-picky, but could you make the variables a little more readable (i.e. `area` in this case)?
</details>
OK

---

*[script.lua, line 1636 \[r1\]](https://reviewable.io:443/reviews/achaeabashingscript/bashing/40#-KMOWBDJdI-0-Srya4mo:-KMOuB8Yp7YcEYdY-qzi:5173665) ([raw file](https://github.com/achaeabashingscript/bashing/blob/a569783a7de58971bc6889af276bb81751787d29/script.lua#L1636)):*
<details><summary><i>Previously, keneanung wrote…</i></summary>
> Same here as above.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/achaeabashingscript/bashing/40)*

**Comment by keneanung** [comment]
Thank you very much :rocket:

**Pull request merged**
