### PR TITLE
Depthswalker Battlerage additions

### PR DESCRIPTION
**Pull request by zylvyn**
This should add Depthswalker support for battlerages...

Am not at home, so can't fully test. 

#46

---
This change is [Reviewable](https://reviewable.io/reviews/achaeabashingscript/bashing/47)

### CODE REVIEW

**Comment by keneanung** [comment]
This seems like a lot of places to take care of. I thought of shuffling the darkwalker abilities in the battlerage table around instead, especially since we need to add given/used afflictions anyways manually...

**Comment by zylvyn** [comment]
It only populates the battlerage table once, right, so simply reshuffling the entries in the table wouldn't be too horrible?  Although I suppose a check to confirm that the admin aren't fixing the BR order before the swap might be in order?

**Comment by keneanung** [comment]
That's what I meant :smile:

**Comment by keneanung** [comment]
I created an alternative (#49), which is the better way to do it (I think)

**Comment by keneanung** [comment]
Superseded by #49

**Pull request closed without merging**
